project_id = "kvehkmfgwkmgsafpkszs"

[functions.interview-chat]
verify_jwt = false

[functions.analyze-resume]
verify_jwt = false

[functions.generate-coding-questions]
verify_jwt = false

[functions.generate-roadmap]
verify_jwt = false
